### PR TITLE
refactoring-shoco

### PR DESCRIPTION
**Pull request by leonardolouie**
#27 

image

cc: @erangot @1601  
Refactoring shoco 
changes ---
1.  transfer aws amplify result to global state using react-redux so we can freely use it any components in just one using of aws amplify 
2.  created various components for less duplcation 
3.  transfer all the fetch function to react-redux of the ff: 
      -video details 
     -video comments
     -video analytics 
     -video engaged

### CODE REVIEW

**Comment by leonardolouie** [comment]
image


succes in local build :) !hahahaah

**Comment by 1601** [comment]
Re running deployment. - Hopefully this pass in. There are no logs from last one.

cc: @leonardolouie 

@erangot kindly review this pull request =)

**Comment by erangot** [comment]
@1601 working on it now! Thanks!

**Comment by leonardolouie** [comment]
@erangot  okay thanks :)

**Pull request merged**
