### PR TITLE
redux-gatsby

### PR DESCRIPTION
**Pull request by leonardolouie**
converting authentication to redux .. @1601

### CODE REVIEW

**Comment by leonardolouie** [comment]
Hello @erangot this is the new update for feature of the Shoco site. still not running in production but in local development I think it's running ... I add something into src folder a new actions and reducer folder so you can check all the things I wrote there.. thanks :)

**Comment by erangot** [comment]
Hi @leonardolouie consider changing these lines to the green highlighted ones:

video-page.js
image

userReducer.js
image

**Comment by 1601** [comment]
Hello, I can take this as a reviewer for today. 👨‍💻

**Comment by 1601** [comment]
HI @leonardolouie , the window is being used from the node modules of a youtube dependency - you need to remove it - I think it is from the video.js dependecies added by @MiguelQXXV.

**Comment by leonardolouie** [comment]
@1601 got it <3

**Comment by 1601** [comment]
Is this ready for review @leonardolouie? 

🕵

**Comment by 1601** [comment]
Needs fixing on production building.

**Pull request closed without merging**
